### ISSUE TITLE
[APP REQUEST] Piped

### ISSUE THREAD

**Issue by iBicha** [runtipi/runtipi-appstore#412]
Have you considered adding the app yourself? 
- Just creating this issue to track it

**Describe app**
A Youtube frontend, Similar to Invidious

**Links**
https://github.com/TeamPiped/Piped
https://piped.video/
https://docs.piped.video/docs/self-hosting/

**Comment by iBicha** [comment]
cc @FireMasterK Piped would be a good addition to Tipi!

**Comment by FireMasterK** [comment]
I think it would be nice indeed!

Having a look at https://github.com/TeamPiped/Piped-Docker/tree/main/template would be a good start to see how to create an appropriate docker-compose file for a good step. I can always assist in case there are any questions, Piped is a polylithic application, so it could be more complex to wire all the components together.

Some quick notes:
Piped requires you to be reachable over the internet for subscriptions to work due to pubsub. If someone is behind a NAT, something like ngrok, tailscale funnel, or Cloudflare tunnels could be used.

**Comment by kubo6472** [comment]
I achieved some success with tailscale lately, but I found this repo: https://github.com/pgrok/pgrok might be more desirable for the implementation here instead.

**Comment by steveiliop56** [comment]
Hello @iBicha, thank you for your submission! Unfortunately the app requires running custom commands before running and tipi can't do this at the moment...
